version: "3"
services:
  home_automation:
    image: registry.gitlab.com/mithem/home_automation:latest
    container_name: home_automation
    volumes:
      - /mnt/MassStorage/Hausaufgaben/HAs:/homework/current
      - /mnt/MassStorage/Hausaufgaben/Archive:/homework/archive
    environment:
      EMAIL_ADDRESS: test@example.com
      EMAIL_PASSWD: passw0rd!
      HASS_BASE_URL: http://homeassistant.local:8123
      HASS_TOKEN: t0ken!
      THINGS_SERVER_URL: http://things.local:8001
      COMPOSE_FILE: /docker-compose.yml
