#!/bin/bash
echo "Please enter your password in order for it to be cached for the later commands."
sudo echo "Thanks!"
sudo apt-get update && sudo apt-get install -y nmap net-tools neovim cockpit bluez texlive-latex-extra
script/install-system-dependencies
pip3 install -r requirements.txt
sudo python3 setup.py install &
wait
echo "\n\nInstalled packages."
