name: CI

on:
  - push
  - pull_request
  - workflow_dispatch
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python
        uses: actions/setup-python@v3.1.2
        with:
          python-version: 3.10
      - name: Copy config files
        run: cp home_automation_ci.conf.yml home_automation.conf.yml
      - name: Install tox
        run: pip3 install -r requirements.txt | grep tox
      - name: Run tox
        run: tox
