name: tag-release

on:
  - push
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: GitHub Create Tag Release
        uses: Roang-zero1/github-create-release-action@v2.1.0
        with:
          version_regex: ^v[[:digit:]]+\.[[:digit:]]+\.[[:digit:]]+
          prerelease_regex: ^v[[:digit:]]+\.[[:digit:]]+\.[[:digit:]]+-?(a|b)[[:digit:]]+