name: tag-release

on:
  - push
  - create
jobs:
  tag-release:
    runs-on: ubuntu-latest
    steps:
      - name: GitHub Create Tag Release
        uses: Roang-zero1/github-create-release-action@v2.1.0
        continue-on-error: true
        with:
          version_regex: ^v[[:digit:]]+\.[[:digit:]]+\.[[:digit:]]+
          prerelease_regex: ^v[[:digit:]]+\.[[:digit:]]+\.[[:digit:]]+-?(a|b)[[:digit:]]+
